name: Compilar y desplegar

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/compilar-desplegar.yml'
      - 'GithubActionsDemoApp/**'
      - 'Pruebas/**'
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      proyecto: GithubActionsDemoApp/GithubActionsDemoApp.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 8.0.x

    - name: Obteniendo dependencias
      run: dotnet restore

    - name: Compilar
      run: dotnet build --no-restore

    - name: Test y validaciones
      run: dotnet test --no-build

    - name: dotnet publish
      run: dotnet publish $proyecto -c Release -o ${{ github.workspace }}/miapp --runtime win-x86

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        path: ${{ github.workspace }}/miapp
        name: build
        
    - name: zip
      if: startsWith(github.ref, 'refs/tags/')
      run: zip -r ${{ github.workspace }}/mi_app.zip ${{ github.workspace }}/miapp

    - name: Verificar archivo zip
      if: startsWith(github.ref, 'refs/tags/')
      run: ls -lh ${{ github.workspace }}/mi_app.zip

    - name: GH Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/mi_app.zip
        body: "Nuestra aplicación"
        tag_name: ${{ github.ref_name }}
